apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: dn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dn 
  name: dn
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dn
    weight: 100 
