apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dn 
  janus-idp.io/tekton: dn
  backstage.io/kubernetes-id: dn
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dn
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  